require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
platform :ios, '10.0'

target 'SwipeyReddit' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'SwipeyRedditTests' do
    inherit! :complete
    # Pods for testing
  end
  pod 'React-RCTLinking', :path=> '../node_modules/react-native/Libraries/LinkingIOS'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
     end
  end
end

target 'SwipeyReddit-tvOS' do
  # Pods for SwipeyReddit-tvOS

  target 'SwipeyReddit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
